[tool.poetry]
name = "oc-graphenricher"
version = "0.2.4"
description = "A tool to enrich any OCDM compliant Knowledge Graph, finding new identifiers and deduplicating entities"
authors = ["Gabriele Pisciotta <ga.pisciotta@gmail.com>"]
license = "ISC"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
tqdm = "4.47.0"
requests = "2.22.0"
networkx = "2.5"
oc-ocdm = "7.3.1"
python-levenshtein = "0.12.2"
requests-cache = "0.6.0"
rdflib = "6.3.2"
levenshtein = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = 'scripts:test'
